#!/usr/bin/env python3

import argparse
import os
import sys
import svgwrite
from svgwrite import cm, mm, px


# Params
x_offset = 0
y_offset = 0
height = 4
width = 8
arrow_thickness = 2
arrowhead_thickness = 4
arrowhead_length = 3
scale = 100.0

# Calc

scaled_x_offset = x_offset * scale
scaled_y_offset = y_offset * scale
scaled_height = height * scale
scaled_width = width * scale
scaled_arrow_thickness = arrow_thickness * scale
scaled_arrowhead_thickness = arrowhead_thickness * scale
scaled_arrowhead_length = arrowhead_length * scale

x_min = scaled_x_offset
x_left_arrow = scaled_x_offset + scaled_arrowhead_length
x_right_arrow = scaled_x_offset + scaled_width - scaled_arrowhead_length
x_mid = (scaled_width / 2) + scaled_x_offset
x_max = scaled_width + scaled_x_offset
y_min = scaled_y_offset
y_mid = scaled_y_offset + (scaled_height/2.0)
y_max = scaled_y_offset + scaled_height
y_head_min = y_mid - (scaled_arrowhead_thickness / 2.0)
y_head_max = y_mid + (scaled_arrowhead_thickness / 2.0)
y_arrow_min = y_mid - (scaled_arrow_thickness/2.0)
y_arrow_max = y_mid + (scaled_arrow_thickness/2.0)
y_mid = (y_arrow_min + y_arrow_max) / 2
canvas = svgwrite.Drawing(
    filename="rarr.svg",
    debug=True,
    size=('%dmm' % (scaled_width),'%dmm' % (scaled_height)),
    viewBox=('0 0 %d %d' %(scaled_height+30,scaled_width))
)
style = "fill:#CCCCCC;stroke:black;stroke-scaled_width:3;alpha=0.5"
#o = canvas.path(d="M  0,200 L 200,400 L 200,300 L 800,300 L 800,100 L 200,100 L 200,0 Z",id="left-arrow",style="fill:#CCCCCC;alpha=0.5")
#o = canvas.path(d="M  0,100 L 0,300 L 600,300 L 600,400 L 800,200 L 600,0 L 600,100 Z",id="right-arrow",style="fill:#CCCCCC;alpha=0.5")
#o = canvas.path(d="M  0,2 L 2,4 L 2,3 L 6,3 L 6,4 L 8,2 L 6,0 L 6,1 L 2,1 L 2,0 Z",id="right-arrow",style="fill:#CCCCCC;alpha=0.5")

o = canvas.path(
    d=['M', x_min,         y_mid,
        'L', x_left_arrow,  y_head_max,
        'L', x_left_arrow,  y_arrow_max,
        'L', x_right_arrow, y_arrow_max,
        'L', x_right_arrow, y_head_max,
        'L', x_max,         y_mid,
        'L', x_right_arrow, y_head_min,
        'L', x_right_arrow, y_arrow_min,
        'L', x_left_arrow,  y_arrow_min,
        'L', x_left_arrow,  y_head_min,
        'Z'],
    id="double-arrow",
    style="fill:#CCCCCC;alpha=0.5")
o = canvas.path(
    d=['M', x_min,  y_arrow_max,
        'L', x_right_arrow, y_arrow_max,
        'L', x_right_arrow, y_head_max,
        'L', x_max,         y_mid,
        'L', x_right_arrow, y_head_min,
        'L', x_right_arrow, y_arrow_min,
        'L', x_min,         y_arrow_min,
        'Z'],
    id="right-arrow",
    style="fill:#CCCCCC;alpha=0.5")
o = canvas.path(
    d=['M', x_min,         y_mid,
        'L', x_left_arrow,  y_head_max,
        'L', x_left_arrow,  y_arrow_max,
        'L', x_max,         y_arrow_max,
        'L', x_max,         y_arrow_min,
        'L', x_left_arrow,  y_arrow_min,
        'L', x_left_arrow,  y_head_min,
        'Z'],
    id="left-arrow",
    style="fill:#CCCCCC;alpha=0.5")
#o = canvas.path(d="M -4,1 L 1,1 L 1,2 L 4,0 L 1,-2 L 1,-1 L 1,-4 Z",id="right-arrow")
#    d="M -4,1 L 1,1 L 1,2 L 4,0 L 1,-2 L 1,-1 L -4,-1 Z",
#    d="M 1,8 C 1.05,8.3308271 1.34,9.0025063 1.21,9.3333333 H -4 V 10.666667 H 1.2 C 1.33,10.997494 1.03,11.679198 0.99,12 2.17,11.759398 3.24,10.766917 4,9.9949875 3.24,9.2330827 2.17,8.2406015 1,8 Z"
#    d="m 1,295 c 0.05,0.33 0.34,1.0 0.21,1.33 H -4 v 1.33 h 5.20 c 0.13,0.33 -0.17,1.01 -0.21,1.33 1.18,-0.24 2.25,-1.23 3.01,-2 C 3.24,296.23 2.17,295.24 1,295 Z"
for x in range(width + 1):
    canvas.add(canvas.line(start=(x*scale,0), end=(x*scale,height*scale),style="stroke:#FF0000;stroke-width:0.1;alpha=0.5"))
    pass
for y in range(height + 1):
    canvas.add(canvas.line(start=(0,y*scale), end=(width*scale,y*scale),style="stroke:#00FF00;stroke-width:0.1;alpha=0.5"))
    pass
canvas.add(o)
# for x in range(9):
#     x1 = x * 100
#     for y in range(5):
#         print(x,y)
#         y1 = y * 100
#         canvas.add(canvas.text("(%d,%d)" %(x1,y1), insert=(x1-5,y1+10)))
#         pass
#     pass
canvas.add(canvas.text("x_min", insert=(x_min,y_max + 10)))
canvas.add(canvas.text("x_left_arrow", insert=(x_left_arrow,y_max + 10)))
canvas.add(canvas.text("x_mid", insert=(x_mid,y_max + 10)))
canvas.add(canvas.text("x_right_arrow", insert=(x_right_arrow,y_max + 10)))
canvas.add(canvas.text("x_max", insert=(x_max,y_max + 10)))
canvas.add(canvas.text("y_min", insert=(x_min,y_min)))
canvas.add(canvas.text("y_head_min", insert=(x_min,y_head_min)))
canvas.add(canvas.text("y_arrow_min", insert=(x_min,y_arrow_min)))
canvas.add(canvas.text("y_mid", insert=(x_min,y_mid)))
canvas.add(canvas.text("y_arrow_max", insert=(x_min,y_arrow_max)))
canvas.add(canvas.text("y_head_max", insert=(x_min,y_head_max)))
#canvas.add(canvas.text("", insert=(x_min,)))
canvas.save()
